app.py
from flask import Flask
from flask_migrate import Migrate
from flask_wtf.csrf import CSRFProtect  # csrf

from db_connect import db
import config
import secrets


def create_app():
    app = Flask(__name__)

    app.config.from_object(config)

    csrf = CSRFProtect()
    csrf.init_app(app)

    db.init_app(app)
    Migrate().init_app(app, db, render_as_batch=True)

    from views import main_view
    import model
    app.register_blueprint(main_view.bp)

    # 세션 암호화 => 서버가 정보를 암호화 해서 가지고 있겠다는 뜻
    secret_key = secrets.token_hex(16)
    app.config['SECRET_KEY'] = secret_key
    app.config['SESSION_TYPE'] = 'filesystem'

    return app


if __name__ == '__main__':
    create_app().run()

views/auth_view.py
from flask import Blueprint, render_template, url_for, request, session, flash, g
# from flask_wtf import csrf
from model import *
from werkzeug.utils import redirect
from bcrypt import hashpw, checkpw, gensalt

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/login', methods=('GET',))
def login_try():
    return render_template('login.html')


@bp.route('/login', methods=['POST'])
def login():
    user_id = request.form['user_id']
    user_pw = request.form['user_pw']

    user_data = User.query.filter_by(user_id=user_id).first()

    if not user_data:
        flash("존재하지 않는 아이디입니다.")
        # user_id 다시 그대로 넘겨주기
        return redirect(url_for('auth.login_try'))

    elif not checkpw(user_pw.encode('utf-8'), user_data.user_pw):
        flash("비밀번호가 일치하지 않습니다.")
        return redirect(url_for('auth.login_try'))
    else:
        session.clear()

        session['user_id'] = user_id
        session['user_nickname'] = user_data.user_nickname

        flash(f'안녕하세요, {user_data.user_nickname}님!')
        return redirect(url_for('main.home'))


@bp.route('/logout', methods=['GET'])
def logout():
    session.clear()
    flash('로그아웃 되었습니다.')
    return redirect(url_for('main.home'))


@bp.route('/join', methods=['GET'])
def join():
    return render_template('join.html')


@bp.route('/join', methods=['POST'])
def register():
    user_id = request.form['user_id']
    tmp_pw = request.form['user_pw']

    user = User.query.filter_by(user_id=user_id).first()

    # 비밀번호 규칙 :8자리 이상(4자리 이상 문자 + 2자리 이상 숫자 + 2자리 이상 특수문자)
    check = [0] * len(tmp_pw)
    for i in range(len(tmp_pw)):
        if tmp_pw[i].isdigit():
            check[i] = 'digit'
        elif tmp_pw[i].isalpha():
            check[i] = 'alpha'
        else:
            check[i] = 'sign'
    if check.count('digit') < 2 or check.count('alpha') < 4 or check.count('sign') < 2:
        flash('비밀번호는 4자리 이상의 문자, 2자리 이상의 숫자, 2자리 이상의 특수문자가 포함되어야 합니다.')
        return redirect(url_for('auth.join'))

    # 등록된 사용자가 아닐 경우 가입 시작
    if not user:
        user_pw_check = request.form['user_pw_check']
        if len(tmp_pw) < 8:
            flash('비밀번호는 9자리 이상이어야 합니다.')
            return redirect(url_for('auth.join'))

        elif tmp_pw != user_pw_check:
            flash('비밀번호가 일치하지 않습니다.')
            return redirect(url_for('auth.join'))

        # 패스워드 해쉬
        user_pw = hashpw(tmp_pw.encode('utf-8'), gensalt())
        user_name = request.form['user_name']
        user_nickname = request.form['user_nickname']
        user_email = request.form['user_email']

        user = User(user_id=user_id, user_pw=user_pw, user_name=user_name,
                    user_nickname=user_nickname, user_email=user_email)

        db.session.add(user)
        db.session.commit()
    # 등록된 사용자일 경우 안내메시지
    else:
        flash('사용할 수 없는 아이디입니다.')
        return "사용할 수 없는 아이디입니다."
    return redirect(url_for('main.home'))

views/main_view.py
# TODO 장르 카테고리, 책 제목 모델 추가하기, 책 API 가져오기
# TODO 다 읽은 것, 현재 진행형 카테고리 추가
# TODO <form id="signup" action="{{url_for('main.join')}}" method="post">{{form.csrf_token}} 해결하기
from flask import Blueprint, render_template, url_for, request, session, flash, g
# from flask_wtf import csrf
from model import *
from werkzeug.utils import redirect
from bcrypt import hashpw, checkpw, gensalt

bp = Blueprint('main', __name__)


@bp.route('/')
def home():
    post_list = Post.query.order_by(Post.created_at.desc()).all()
    return render_template('index.html', post_list=post_list)

views/mypage_view.py
from flask import Blueprint, render_template, url_for, request, session, flash, g
# from flask_wtf import csrf
from model import *
from werkzeug.utils import redirect
from bcrypt import hashpw, checkpw, gensalt

bp = Blueprint('mypage', __name__, url_prefix='/mypage')


@bp.route('/posts', methods=['GET'])
def myposts():
    if session['user_id']:
        user_id = session['user_id']
        post_list = Post.query.filter_by(user_id=user_id).all()
        return render_template('mypage.html', post_list=post_list)

views/post_view.py
from flask import Blueprint, render_template, url_for, request, session, flash, g
# from flask_wtf import csrf
from model import *
from werkzeug.utils import redirect
from bcrypt import hashpw, checkpw, gensalt

bp = Blueprint('post', __name__, url_prefix='/post')


@bp.route('/post/<int:post_id>', methods=['GET'])
def post_detail(post_id):
    post = Post.query.filter_by(id=post_id).first()
    return render_template('post_detail.html', post=post)


@bp.route('/create-post', methods=['POST'])
def create_post():
    content = request.form['content']
    title = request.form['title']
    # join 이용해 닉네임으로 고치기
    user_id = session['user_id']

    post = Post(user_id, title, content)

    db.session.add(post)
    db.session.commit()

    flash('성공적으로 작성 되었습니다!')
    return redirect(url_for('post.post_detail', post_id=post.id))


@bp.route('/create-post', methods=['GET'])
def create_try():
    return render_template('post_create.html')


@bp.route('/update-post/<int:post_id>', methods=['POST'])
def update_post(post_id):
    post = Post.query.filter_by(id=post_id).first()

    content = request.form['content']
    title = request.form['title']

    post.title = title
    post.content = content

    db.session.commit()

    flash('성공적으로 수정 되었습니다!')
    return redirect(url_for('post.post_detail', post_id=post.id))


@bp.route('/update-post/<int:post_id>', methods=['GET'])
def update_try(post_id):
    post = Post.query.filter_by(id=post_id).first()

    return render_template('post_update.html', post=post)


@bp.route('/delete-post/<int:post_id>')
def delete_post(post_id):
    post = Post.query.filter_by(id=post_id).first()

    db.session.delete(post)
    db.session.commit()

    flash('정상적으로 삭제 되었습니다.')
    return redirect(url_for('main.home'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap.min.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='index.css') }}" />
    <script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='popper.min.js') }}"></script>
    {% block style %}{% endblock style %}
    <title>책벌레</title>
</head>
<body>
    <header>
        <div id="warp">
            <nav class="navbar navbar-expand-sm bg-light">
                    <ul id="nav-title"class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.home')}}">책벌레</a>
                        </li>
                    </ul>
                    <ul id="nav-right">
                        {% if session['user_id'] %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('mypage.myposts') }}">{{session['user_id']}}님의 글귀</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.logout') }}">로그아웃</a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ url_for('post.create_post')}}">
                                <button type="button" class="btn_post">
                                    글귀 작성하기
                                </button>
                            </a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.login') }}">로그인</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.join') }}">회원가입</a>
                        </li>
                        {% endif %}
                    </ul>



            </nav>
        </div>
    </header>
    <div id="flash">
        {% for message in get_flashed_messages() %}
        <div class="flash alert alert-info">
            {{message}}
        </div>
        {% endfor %}
    </div>
    <div id="content">

    {% block content %}{% endblock content %}
    </div>
    <div id="footer">
        <div class="footer">
            <p>책벌레</p>
        </div>
    </div>

    {% block jscontent %}{% endblock jscontent %}

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block style %}
    
{% endblock style %}
{% block content %}
    {% if post_list %}
    <div class="post_container">
        {% for post in post_list %}
        <a href="{{ url_for('main.post_detail', post_id=post.id)}}">
            <div class="post">
                <h2 class="title">{{post.title}}</h2>
                <p class="text">{{post.content[:50]}}</p>
                <p class="date">{{post.created_at.strftime('%Y-%M-%d %H:%M:%S')}}</p>
            </div>
        </a>
        {% endfor %}
    </div>
    {% else %}
    <div class="blank">
        <p>보여줄 글이 없어요.<br>첫 글을 작성해 보세요!</p>
    </div>
{% endif %}


{% endblock content %}

templates/join.html
{% extends 'base.html' %}
{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='join.css') }}">
{% endblock style %}
{% block content %}
<div class="container">
    <div class="header">
        <h3>회원가입</h3>
    </div>
    <div class="sep"></div>

    <div class="inputs">
        <form id="signup" action="{{url_for('auth.join')}}" method="post">
            <input type="id" placeholder="아이디를 입력하세요." name="user_id" autofocus />
            <input type="password" placeholder="비밀번호를 입력하세요." name="user_pw" />
            <input type="password" placeholder="비밀번호를 다시 한 번 입력하세요." name="user_pw_check" />
            <input type="text" placeholder="이름을 입력하세요." name="user_name" />
            <input type="email" placeholder="이메일을 입력하세요." name="user_email" />
            <input type="text" placeholder="닉네임을 입력하세요." name="user_nickname" />
            <input id="submit" type="submit" value="가입하기">
         </form>
    </div>
​</div>
{% endblock content %}

templates/login.html
{% extends 'base.html' %}
{% block style %}
        <link rel="stylesheet" href="{{ url_for('static', filename='login.css') }}">
{% endblock style %}
{% block content %}
    <div class="wrapper">
        <form class="form-signin" action="{{url_for('auth.login')}}" method="post">
            <h2 class="form-signin-heading">로그인 하기</h2>
            <input type="text" class="form-control" name="user_id" placeholder="아이디를 입력하세요" required=""
                autofocus="" />
            <input type="password" class="form-control" name="user_pw" placeholder="비밀번호를 입력하세요" required="" />
            <label class="checkbox">
                <input type="checkbox" value="remember-me" id="rememberMe" name="rememberMe"> Remember me
            </label>
            <input class="btn btn-primary" type="submit" value="로그인">
        </form>
    </div>
{% endblock content %}

templates/mypage.html
{% extends './base.html' %}
{% block content %}
    {% if post_list %}
    <div class="post_container">
        {% for post in post_list %}
        <a href="{{ url_for('post.post_detail', post_id=post.id)}}">
            <div class="post">
                <h2 class="title">{{post.title}}</h2>
                <p class="text">{{post.content[:50]}}</p>
                <p class="date">{{post.created_at.strftime('%Y-%M-%d %H:%M:%S')}}</p>
            </div>
        </a>
        {% endfor %}
    </div>
    {% else %}
    <div class="blank">
        <p>보여줄 글이 없어요.<br>첫 글을 작성해 보세요!</p>
    </div>
    {% endif %}
{% endblock content %}

templates/post_create.html
{% extends 'base.html' %}
{% block content %}
{% if session['user_id'] %}
<form action="{{ url_for('post.create_post') }}" method="post">
    <div class="form-group">
        <input class="form-control" name="title" id="title" placeholder="제목을 작성하세요.">
        <input class="form-control" name="content" id="content" placeholder="당신의 글귀를 남겨주세요!">
    </div>
    <input class="btn btn-primary" type="submit" value="글귀 등록하기">
</form>
{% else %}
    <p>로그인 후 이용 가능합니다.</p>
{% endif %}
{% endblock content %}

templates/post_detail.html
{% extends 'base.html' %}
{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='post_detail.css') }}">
{% endblock style %}
{% block js %}
    <script src="{{ url_for('static', filename='jquery-3.6.0.min.js') }}"></script>
{% endblock js %}

{% block content %}
    <div class="container">
        <h1 class="title">{{post.title}}</h1>
        <p class="date">{{post.created_at}}</p>
        <p class="date">작성자 | {{post.user_id}}</p>
    </div>

    <div class="content">
        <p class="text">{{post.content}}</p>
    </div>
    {% if session['user_id'] == post.user_id %}
        <a href="{{ url_for('post.update_post', post_id=post.id)}}">
            <button type="button" class="btn btn-primary">
                수정하기
            </button>
        </a>
        <a href="{{ url_for('post.delete_post', post_id=post.id)}}">
            <button type="button" class="btn btn-primary" id="delete-btn">삭제하기</button>
        </a>
    {% endif %}
{% endblock content %}

templates/post_list.html
{% extends 'base.html' %}

templates/post_update.html
{% extends 'base.html' %}
{% block content %}
    <form action="{{ url_for('post.update_post', post_id=post.id) }}" method="post">
        <div class="form-group">
            <input class="form-control" name="title" id="title" value="{{post.title}}" />
            <input class="form-control" name="content" id="content" value="{{post.content}}" />
               
        </div>
        <input class="btn btn-primary" type="submit" value="수정완료">
    </form>

{% endblock content %}